FROM nginx:alpine

# Copy your configuration to the nginx configuration directory
COPY example.conf /etc/nginx/conf.d/default.conf

# listen on port 80 in this container
EXPOSE 80


#Populate files with st
#VOLUME /static-web-pages-directory
